name: Playwright tests
'on':
#  push:
#    branches:
#      - main
  workflow_dispatch: null
jobs:
  test:
    name: Playwright Tests    
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20           
      - name: Install dependencies
        id: install-dependencies
        run: npm ci
      - name: Install Playwright Browsers
        id: install-playwright-browsers
        run: npx playwright install --with-deps
      - name: Install Playwright System Dependencies
        id: install-playwright-system-dependencies
        run: npx playwright install-deps
      - name: Run Playwright Tests
        id: run-playwright-tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload Playwright Blob Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-blob-report-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: playwright-blob-report/
          if-no-files-found: ignore
          retention-days: 1    
            
  report:
      name: Merge Reports
      if: ${{ always() }}
      runs-on: ubuntu-latest
      needs: [test]
      timeout-minutes: 30    
      steps:
        - name: Checkout Repository
          id: checkout-repository
          uses: actions/checkout@v4
        - name: Setup Node
          id: setup-node
          uses: actions/setup-node@v4
          with:
           node-version: 20 
        - name: Download Playwright Blob Reports
          uses: actions/download-artifact@v4
          with:
           path: playwright-blob-report
           pattern: playwright-blob-report-*
           merge-multiple: true    
        - name: Merge Playwright HTML Reports
          run: npx playwright merge-reports --reporter html ./playwright-blob-report  

