name: Playwright tests
'on':
#  push:
#    branches:
#      - main
  workflow_dispatch: null
jobs:
  test:
    name: Playwright Tests    
    runs-on: ubuntu-latest 
    timeout-minutes: 60    
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]   
    steps:
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20           
      - name: Install dependencies
        id: install-dependencies
        run: npm ci
      - name: Install Playwright Browsers
        id: install-playwright-browsers
        run: npx playwright install --with-deps
      - name: Install Playwright System Dependencies
        id: install-playwright-system-dependencies
        run: npx playwright install-deps
      - name: Run Playwright Tests
        id: run-playwright-tests 
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload Playwright Blob Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-blob-report-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: playwright-blob-report/
          if-no-files-found: ignore
          retention-days: 1          
      - name: Upload Playwright Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: test-results/
          if-no-files-found: ignore
          retention-days: 1    
      - name: Upload Playwright Monocart Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-monocart-report-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: playwright-monocart-report/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Playwright Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ matrix.shardIndex }}_${{ matrix.shardTotal }}
          path: allure-results/
          if-no-files-found: ignore
          retention-days: 1
  report:
      name: Merge and Publish Reports
      if: ${{ always() }}
      runs-on: ubuntu-latest
      needs: [test]
      timeout-minutes: 30
      permissions:
        contents: read
        pages: write
        id-token: write
      concurrency:
        group: 'pages'
        cancel-in-progress: true
      environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
    
      steps:
        - name: Checkout Repository
          id: checkout-repository
          uses: actions/checkout@v4
        - name: Setup Node
          id: setup-node
          uses: actions/setup-node@v4
          with:
           node-version: 20  
        - name: Download Playwright Blob Reports
          uses: actions/download-artifact@v4
          with:
           path: playwright-all-blob-reports
           pattern: playwright-blob-report-*
           merge-multiple: true
        - name: Merge Playwright HTML Reports
          run: npx playwright merge-reports --reporter html ./playwright-all-blob-reports
        - name: Download Monocart Reports
          id: download-monocart-reports
          uses: actions/download-artifact@v4
          with:
           pattern: monocart-report-*   
        - name: Download Test Results
          id: download-test-results
          uses: actions/download-artifact@v4
          with:
           path: merged-monocart-report/data
           pattern: test-results-*
           merge-multiple: true   
        - name: Merge Playwright Monocart Reports
          id: merge-playwright-monocart-reports
          run: |
           npm run merge:report:monocart   
        - name: Download Allure Results
          id: download-allure-results
          uses: actions/download-artifact@v4
          with:
           path: allure-results
           pattern: allure-results-*
           merge-multiple: true         
        - name: Install dependencies
          run: npm install -g allure-commandline
        - name: Generate Allure Report
          id: generate-allure-report
          run: |
           npx allure generate allure-results -o allure-report --clean          
        - name: Move to Reports folder
          id: move-to-reports-folder
          run: |
            mv playwright-report reports/playwright
            mv playwright-monocart-report reports/monocart 
            mv allure-report reports/allure
          shell: bash
        - name: Setup Pages
          uses: actions/configure-pages@v4
        - name: Upload Artifact
          uses: actions/upload-pages-artifact@v3
          with:
           path: reports/
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
