name: Playwright tests
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  test:
    name: Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install Playwright System Dependencies
        run: npx playwright install-deps
      - name: Run Playwright Tests
        run: npx playwright test
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Playwright Monocart Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monocart-report
          path: test-results
          retention-days: 1
      - name: Upload Playwright Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-allure-results
          path: allure-results/
          retention-days: 1
